# @package model

_target_: models.cnn.cnn.CNNModel
model_name: "cnn"

input_channels: 3
num_features: 32
kernel_size: 3
padding: 1
stride: 2 
num_classes: 2
dropout: 0.2
learning_rate: 3e-4
min_learning_rate: 1e-6
weight_decay: 0.01
class_weights: [1.85, 0.69]
eps: 1e-8
