# @package model

_target_: models.yolo11l.yolo11l.PneumoniaYOLO11L
model_name: "yolo11l-cls"

num_classes: 2
learning_rate: 3e-4
min_learning_rate: 1e-6,
weight_decay: 0.1
class_weights: [1.85, 0.69]
