# @package _global_

defaults:
  - data: pneumonia
  - model: vgg16
  - trainer: default
  - _self_

mode: train

project_name: "pneumonia-classification"

run_name: "${model.model_name}-lr_${model.learning_rate}"

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
